name : first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest

        steps: 
          - name: checkout step
            uses: actions@checkout@v4

          - name: first step
            run: echo 'hello world '

          - name: list files
            run: ls 

          - name: Read file
            run: cat Hello.html