name : first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest

        steps: 
          - name: checkout step
            uses: actions/checkout@v4

          - name: list and display the file content
            run: |
              echo 'hello world '
              ls -r
              cat Hello.html
            
          
          # - name: list files
          #   run:  ls

          # - name: Read file
          #   run: cat Hello.html