name : Generate Ascii 
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest

        steps: 
          - name: checkout step
            uses: actions/checkout@v4

          - name: execute the acii script
            run: |
                chmod  -x generat-ascii.sh
                ./generate-ascii.sh
          - name: list the repo files
            run: ls -ltra
                


        #   - name: install cowsay
        #     run: sudo apt install cowsay -y 
            
        #   - name: Generate A AscII Artwork
        #     run: cowsay -f dragon "Run for cover , I am a dragon">>dragon.txt

        #   - name: list files
        #     run:  ls

        #   - name: grep the dragon file
        #     run: grep  -i "dragon" dragon.txt

        #   - name: Read file
        #     run: cat dragon.txt

          
