name: multi-jobs
on: push
jobs:
    build-job:
        runs-on: ubuntu-latest
        steps: 
          - name: checkout step
            uses: actions/checkout@v4

          - name: Install the Cowsay
            run: sudo apt install cowsay -y 

          - name: Execute The Cowsay command
            run: cowsay -f dragon "Run for cover , I am a dragon">>dragon.txt

          - name: upload the artifact
            uses: actions/upload-artifact@v4
            with:
                name: dragon-file
                path: dragon.txt
                        





    test-job:
        needs: build-job
        runs-on: ubuntu-latest
        steps:
            - name: Download the build artifact
              uses: actions/download-artifact@v4
              with:
                 name: dragon-file
            - name: test the file
              run: grep  -i "dragon" dragon.txt





    deployment-job:
        needs: test-job
        runs-on:  ubuntu-latest
        steps:
            - name: Download the build artifact
              uses: actions/download-artifact@v4
              with:
                 name: dragon-file

            - name: Read file
              run: cat dragon.txt
              
            - name: show massage
              run: echo "Deployment ..."



